language: python
cache:
  directories:
  - "$TRAVIS_BUILD_DIR/build/GSL/src"
  - "$TRAVIS_BUILD_DIR/build/FFTW/src"
  - "$TRAVIS_BUILD_DIR/build/SWIG/src"
  - "$TRAVIS_BUILD_DIR/build/CLASS/src"
  - "$TRAVIS_BUILD_DIR/build/ANGPOW/src"
matrix:
  include:
  - os: linux
    python: 2.7
    sudo: required
    env: TOXENV=py27
  - os: linux
    sudo: required
    python: 3.6
    env: TOXENV=py36
  - os: osx
    osx_image: xcode9.4
    language: generic
    env: TOXENV=py27
  - os: osx
    osx_image: xcode9.4
    language: generic
    env: TOXENV=py36
install:
- "./.travis/install.sh"
- source $HOME/miniconda/bin/activate
- source activate test-environment
- cmake --version
- python --version
script:
- export LD_LIBRARY_PATH=$HOME/miniconda/envs/test-environment/lib:/usr/local/lib:$LD_LIBRARY_PATH
- export CPATH=$HOME/miniconda/envs/test-environment/include
- export PKG_CONFIG_PATH=$HOME/miniconda/envs/test-environment/lib/pkgconfig:/usr/local/lib/pkgconfig:$PKG_CONFIG_PATH
- flake8 pyccl
- python setup.py build
- nosetests tests/run_tests.py --all --debug --detailed-errors --verbose --process-restartworker
  --with-coverage --cover-package=pyccl
- make -Cbuild && sudo make -Cbuild install
- check_ccl
after_success:
- coveralls
deploy:
  provider: pypi
  user: desc-ccl
  password:
    secure: HsuTCvOcmuNWM1RfEPy76xma6x9Kv4bgbP1M0IGpKEA2ZxOB4mHc7zCGDS5rvuft/7HQL5LfUaU/vL84cd5ca0CFMqE8WxUTboh8XwY9+3fV7IlOSHlSjmr7etnAEwWsCQ56dE2Ph73f7EAMREg5FeT/i9OsMWrkyPn8z53F6+PeZP84sPLn2t5rerjXR8ZT7xFLZZx4y5qpgV4HwTAIsJWuVixOE/gTFqLD/yJGIJpiOIptD+sTfxWaploYz27JzHiUn5Y+oDluTJ7yuLCkW55SVukEr/IKaNzyEesbGjVYBuUePVvEc7dl8wVudTib4juUBYTM7KZevCBGHi4fn+DHgdK+8rVasY2+AixrnehDYCOhy3T06c79z6F3R5ZFjsYdiaJQrPoAeWCdW8elwJ3N/KuVEWG6e6SzfVAq+laFY1LYbSD7EMGajYaLUf7hdKkDNbuKbIaDmEN0q4BnpFSiDVpR/7PcVCnpfutRiuBEYTM6QTwS4vkrSJIRJYB92KYXZ0h5XqaeYBMTpXyGlBi5Z6lRTydZPgqgSK/YyKoqcmJ8pnBYaJmt+6mPBvb4d/hLiY3n7m6gLWTiIcKHnFuoo3xMLbLEenNU6Y66nT+y7czp1Dw1jFoVaAjyKkQlEcZuJZUnmAhxweXVHR07vaQQeHiStglQni9QKKLk1Lo=
  on:
    tags: true
    branch: master
